import { marked } from "marked";
import { spawn } from "node:child_process";
import type { ChildProcess } from "node:child_process";
import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import prettier from "prettier";
import { scanDocuments } from "./cache";
import type { CachedDocument } from "./cache";
import { buildAskPayload } from "./ask";

const PICO_CSS_URL = "https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.classless.min.css";
const INDEX_HREF = "../index.html";
const HTML_MARKER = "<!-- generated by prosey:content-v3 -->";
const META_SEP = '<span style="opacity: 0.4">&nbsp;&nbsp;|&nbsp;&nbsp;</span>';

let cachedCss: string | null = null;

async function getPicoCss(): Promise<string> {
  if (cachedCss) return cachedCss;
  const res = await fetch(PICO_CSS_URL);
  cachedCss = await res.text();
  return cachedCss;
}

const LOGO_SVG = `<svg width="100" viewBox="92 120 264 68" role="img" title="Prosey" xmlns="http://www.w3.org/2000/svg">
  <title>Prosey</title>
  <path d="M100,545 a4,4 0 0 0-4,4 v50 a4,4 0 0 0 6,3.46 l43,-25 a4,4 0 0 0 0,-6.93 l-43,-25 a4,4 0 0 0-2,-0.53 Z" transform="translate(0,-405)" fill="#9B8BF4" opacity="0.25"/>
  <path d="M96,130 C96,126 99,124 102,126 L145,149 C148,151 148,155 145,157 L102,180 C99,182 96,180 96,176 Z" fill="none" stroke="#9B8BF4" stroke-width="2.5" stroke-linejoin="round"/>
  <path d="M96,130 C96,126 99,124 102,126 L145,149 C148,151 148,155 145,157 L102,180 C99,182 96,180 96,176 Z" fill="#9B8BF4" opacity="0.18"/>
  <path d="M162,142 L178,154 L162,166" fill="none" stroke="#9B8BF4" stroke-width="2.8" stroke-linecap="round" stroke-linejoin="round"/>
  <path d="M176,142 L192,154 L176,166" fill="none" stroke="#9B8BF4" stroke-width="2.8" stroke-linecap="round" stroke-linejoin="round"/>
  <rect x="212" y="138" width="140" height="12" rx="6" fill="#9B8BF4" opacity="0.85"/>
  <rect x="212" y="155" width="116" height="12" rx="6" fill="#9B8BF4" opacity="0.55"/>
  <rect x="212" y="172" width="130" height="12" rx="6" fill="#9B8BF4" opacity="0.3"/>
</svg>`;
const LOGO_DATA_URI = `data:image/svg+xml;charset=utf-8,${encodeURIComponent(LOGO_SVG)}`;

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function watchMetaHtml(
  duration: number,
  wordCount: number,
  videoId: string,
  channelName?: string,
  channelId?: string,
  channelDescription?: string,
): string {
  const sep = META_SEP;
  const h = Math.floor(duration / 3600);
  const m = Math.round((duration % 3600) / 60);
  const durStr = h > 0 ? `${h} h ${m} min` : `${m} min`;
  const readTime = Math.ceil(wordCount / 200);
  const watchUrl = `https://youtube.com/watch?v=${videoId}`;
  let parts = "";
  if (channelName) {
    const chUrl = channelId
      ? `https://youtube.com/channel/${channelId}`
      : `https://youtube.com/@${encodeURIComponent(channelName)}`;
    const chDesc = channelDescription || channelName;
    parts += `<a href="${chUrl}" class="watch-link" title="${escapeHtml(chDesc)}">${escapeHtml(channelName)}</a>${sep}`;
  }
  parts += `<a href="${watchUrl}" class="watch-link">${durStr} watch</a>${sep}${readTime} min read`;
  return parts;
}

export async function formatMd(text: string): Promise<string> {
  try {
    return await prettier.format(text, { parser: "markdown" });
  } catch {
    return text;
  }
}

const THEME_SCRIPT = `(function(){var b=document.getElementById('theme-btn'),icons={auto:'\u{1F4A1}',light:'\u2600\uFE0F',dark:'\u{1F319}'};function apply(m){var t=m;if(t==='auto')t=window.matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light';document.documentElement.setAttribute('data-theme',t);localStorage.setItem('prosey-theme',m);b.textContent=icons[m]}b.addEventListener('click',function(){var m=localStorage.getItem('prosey-theme')||'auto',d=window.matchMedia('(prefers-color-scheme:dark)').matches;apply(d?{auto:'light',light:'dark',dark:'auto'}[m]:{auto:'dark',dark:'light',light:'auto'}[m])});apply(localStorage.getItem('prosey-theme')||'auto')})();`;

const ASK_SCRIPT = `(function(){var el=document.getElementById('ask-payload'),btn=document.getElementById('ask-btn'),status=document.getElementById('ask-status');if(!el||!btn)return;var payload=JSON.parse(el.textContent);function flash(m){if(!status)return;status.textContent=m;status.style.opacity='1';clearTimeout(flash.t);flash.t=setTimeout(function(){status.style.opacity='0'},2000)}function legacy(){try{var t=document.createElement('textarea');t.value=payload;t.setAttribute('readonly','');t.style.position='fixed';t.style.top='-1000px';document.body.appendChild(t);t.select();var ok=document.execCommand('copy');t.remove();return ok}catch(e){return false}}function copy(){if(navigator.clipboard&&navigator.clipboard.writeText){return navigator.clipboard.writeText(payload).then(function(){return true},function(){return legacy()})}return Promise.resolve(legacy())}btn.addEventListener('click',function(){copy().then(function(ok){flash(ok?'Copied':'Copy failed')})})})();`;

function pageHead(css: string, title: string): string {
  return `<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${title ? escapeHtml(title) + " - Prosey" : "Prosey"}</title>
<script>(function(){var m=localStorage.getItem('prosey-theme'),t=m||'auto';if(t==='auto')t=window.matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light';document.documentElement.setAttribute('data-theme',t);if(!m)localStorage.setItem('prosey-theme','auto')})();</script>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:ital,wght@0,300;0,400;0,500;1,300&display=swap" rel="stylesheet">
<style>
${css}
:root {
  --pico-font-family: 'Plus Jakarta Sans', sans-serif;
  --pico-font-size: 120%;
  --pico-line-height: 1.78;
  --pico-font-weight: 300;
  --pico-blockquote-border-color: #9B8BF4;
}
@media (max-width: 767px) {
  :root {
    --pico-font-size: 110%;
    --pico-line-height: 1.50;

  }
}
main.content {
  max-width: 50em;
  margin: 0 auto;
  padding: 0 1rem;
}
@media (max-width: 767px) {
  main.content {
    margin-top: 0rem;
  }
}

h1 { --pico-font-size: 1.9rem; }
h2 { --pico-font-size: 1.5rem; }
h3 { --pico-font-size: 1.25rem; }
h4 { --pico-font-size: 1.1rem; }
h5 { --pico-font-size: 1rem; }
h6 { --pico-font-size: 0.85rem; }
h1, h2, h3, h4, h5, h6 {
  --pico-font-weight: 500;
  --pico-line-height: 1.25;
  margin-top: 0.1em;
  margin-bottom: 0.666em;
}
h1 {
  letter-spacing: -0.03em;
  margin-top: calc(var(--pico-typography-spacing-vertical) * 2);
  margin-bottom: calc(var(--pico-typography-spacing-vertical) * 2);
}
@media (max-width: 767px) {
  h1 {
    margin-top: calc(var(--pico-typography-spacing-vertical) * 2);
    margin-bottom: calc(var(--pico-typography-spacing-vertical) * 2);
    text-align: center;
  }
}

li:last-child {
  margin-bottom: 0px;
}
blockquote {
  font-style: italic;
  font-size: 1.05rem;
  color: var(--pico-muted-color);
  padding-top: 0;
  padding-bottom: 0;
}
blockquote:first-child { margin-top: 0; }
blockquote:last-child { margin-bottom: 0; }
* { transition: all 0.3s; }
#theme-btn, #theme-btn:focus, #theme-btn:active, #theme-btn:hover { box-shadow: none !important; }
#theme-btn:focus, #theme-btn:active { outline: none !important; }
#theme-btn:hover, #theme-btn:focus, #theme-btn:active { opacity: 1 !important; }
img[alt="Prosey"] { filter: grayscale(100%); }
img[alt="Prosey"]:hover, img[alt="Prosey"]:active, img[alt="Prosey"]:focus { filter: grayscale(0%); }
.watch-link { color: inherit; text-decoration: none; }
.watch-link:hover { text-decoration: underline; }
.doc-item { margin-bottom: 1rem; padding-bottom: 1rem; border-bottom: 1px solid var(--pico-muted-border-color); }
:root:not([data-theme=dark]) .doc-item { border-bottom-color: #c8cdd6; }
.doc-item:first-child { margin-top: 8rem; }
.doc-item:last-child { border-bottom: none; margin-bottom: 0; }
.doc-title { color: inherit; text-decoration: underline; }
.doc-meta { color: var(--pico-muted-color); font-size: 0.9rem; margin: 0; }
.doc-badges { margin: 0.5rem 0 0; }
.doc-badges a { margin-right: 0.75rem; text-decoration: none; }
.doc-badges a:hover { text-decoration: underline; }
#ask-wrap { position: relative; display: inline-block; }
#ask-btn { background: none; border: none; padding: 0; margin: 0; font: inherit; color: inherit; cursor: pointer; }
#ask-btn:hover, #ask-btn:focus, #ask-btn:active { background: none !important; box-shadow: none !important; }
#ask-status { position: absolute; left: 100%; top: 0; padding-left: .5rem; color: var(--pico-muted-color); opacity: 0; transition: opacity .3s; white-space: nowrap; }
</style>
</head>`;
}

const THEME_BUTTON = `<button id="theme-btn" type="button" style="background:none;border:none;cursor:pointer;padding:0;line-height:1;opacity:.5;filter:grayscale(100%);transition:all 0.3s;flex-shrink:0">💡</button>`;

function copyLinkHtml(): string {
  return `<span id="ask-wrap"><button id="ask-btn" type="button" class="watch-link" title="Copy this summary to the clipboard">Copy</button><span id="ask-status" aria-live="polite"></span></span>`;
}

function pageHeader(centerHtml: string, logoHref?: string, askPayload?: string): string {
  const logo = `<img src="${LOGO_DATA_URI}" alt="Prosey" title="Prosey" style="vertical-align:top;flex-shrink:0">`;
  const center = askPayload
    ? `${centerHtml}${centerHtml ? META_SEP : ""}${copyLinkHtml()}`
    : centerHtml;
  return `<div style="display:flex;align-items:center;justify-content:space-between;padding:1rem 1rem 0">
${logoHref ? `<a href="${logoHref}" style="flex-shrink:0">${logo}</a>` : logo}
<div style="flex:1;text-align:center;font-size:.85rem;color:var(--pico-muted-color)">${center}</div>
${THEME_BUTTON}
</div>`;
}

function escapeJson(text: string): string {
  return JSON.stringify(text).replace(/</g, "\\u003c");
}

export async function generateHtml(
  markdown: string,
  title?: string,
  watchMeta?: {
    videoId: string;
    duration: number;
    wordCount: number;
    channelName?: string;
    channelId?: string;
    channelDescription?: string;
  },
  askPayload?: string,
): Promise<string> {
  const [css, body] = await Promise.all([getPicoCss(), marked.parse(markdown)]);
  const payloadTag = askPayload
    ? `<script type="application/json" id="ask-payload">${escapeJson(askPayload)}</script>\n`
    : "";
  const scripts = askPayload ? `${THEME_SCRIPT}\n${ASK_SCRIPT}` : THEME_SCRIPT;

  return `<!DOCTYPE html>
<html lang="en">
${pageHead(css, title ?? "")}
<body>
${HTML_MARKER}
${pageHeader(watchMeta ? watchMetaHtml(watchMeta.duration, watchMeta.wordCount, watchMeta.videoId, watchMeta.channelName, watchMeta.channelId, watchMeta.channelDescription) : "", INDEX_HREF, askPayload)}
<main class="content">
${body}
</main>
${payloadTag}<script>
${scripts}
</script>
</body>
</html>`;
}

function formatDate(ts: number): string {
  const d = new Date(ts);
  const date = d.toLocaleDateString("en-US", { month: "short", day: "2-digit" });
  const time = d.toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit", hour12: false });
  return `${date} ${time}`;
}

function watchAndRead(seconds: number, wordCount: number): string {
  const h = Math.floor(seconds / 3600);
  const m = Math.round((seconds % 3600) / 60);
  const dur = h > 0 ? `${h} h ${m} min watch` : `${m} min watch`;
  return `${dur}${META_SEP}${Math.ceil(wordCount / 200)} min read`;
}

export function generateIndexHtml(docs: CachedDocument[]): Promise<string> {
  const items = docs
    .slice()
    .sort((a, b) => {
      const aTime = Math.max(a.summary?.mtime ?? 0, a.transcript?.mtime ?? 0);
      const bTime = Math.max(b.summary?.mtime ?? 0, b.transcript?.mtime ?? 0);
      return bTime - aTime;
    })
    .map((doc) => {
      const title = escapeHtml(doc.title);
      const metaParts = [];
      if (doc.channel) metaParts.push(escapeHtml(doc.channel));
      const wordCount = Math.max(doc.summary?.wordCount ?? 0, doc.transcript?.wordCount ?? 0);
      if (wordCount > 0) metaParts.push(watchAndRead(doc.duration, wordCount));
      const latest = Math.max(doc.summary?.mtime ?? 0, doc.transcript?.mtime ?? 0);
      if (latest > 0) metaParts.push(formatDate(latest));
      const meta = metaParts.join(META_SEP);
      const entry = doc.dir.split(/[\\/]/).pop();
      const primary =
        doc.summary?.htmlPath ||
        doc.transcript?.htmlPath ||
        doc.summary?.mdPath ||
        doc.transcript?.mdPath;
      const primaryHref = primary ? `${entry}/${primary.split(/[\\/]/).pop()}` : "#";
      const badge = (label: string, item?: { htmlPath?: string; mdPath: string }) => {
        if (!item) return "";
        const href = item.htmlPath
          ? `${entry}/${item.htmlPath.split(/[\\/]/).pop()}`
          : `${entry}/${item.mdPath.split(/[\\/]/).pop()}`;
        return `<a href="${href}" class="doc-badge">[${label}]</a>`;
      };
      const badges = [badge("Summary", doc.summary), badge("Transcript", doc.transcript)].join("");
      return `<div class="doc-item">
<h3><a href="${primaryHref}" class="doc-title">${title}</a></h3>
<p class="doc-meta">${meta}</p>
<p class="doc-badges">${badges}</p>
</div>`;
    })
    .join("\n");

  return (async () => {
    const css = await getPicoCss();
    return `<!DOCTYPE html>
<html lang="en">
${pageHead(css, "Index")}
<body>
${pageHeader(`${docs.length} ${docs.length === 1 ? "document" : "documents"}`)}
<main class="content">
${items}
</main>
<script>
${THEME_SCRIPT}
</script>
</body>
</html>`;
  })();
}

async function writeDocumentHtml(
  doc: CachedDocument,
  kind: "summary" | "transcript",
  item: { mdPath: string; htmlPath?: string; wordCount: number },
): Promise<void> {
  const md = await readFile(item.mdPath, "utf8");
  const html = await generateHtml(
    await formatMd(md),
    doc.title,
    {
      videoId: doc.dir.split(/[\\/]/).pop()!.slice(0, 11),
      duration: doc.duration,
      wordCount: item.wordCount,
      channelName: doc.channel,
      channelId: doc.channelId,
      channelDescription: doc.channelDescription,
    },
    kind === "summary" ? buildAskPayload(md) : undefined,
  );
  await writeFile(join(doc.dir, `${kind}.html`), html, "utf8");
}

export async function rebuildIndex(baseDir: string): Promise<string | null> {
  const docs = await scanDocuments(baseDir);
  for (const doc of docs) {
    for (const kind of ["summary", "transcript"] as const) {
      const item = doc[kind];
      if (!item) continue;
      const existing = item.htmlPath ? await readFile(item.htmlPath, "utf8").catch(() => "") : "";
      if (existing.includes(HTML_MARKER)) continue;
      await writeDocumentHtml(doc, kind, item);
      item.htmlPath = join(doc.dir, `${kind}.html`);
    }
  }
  const indexPath = join(baseDir, "index.html");
  await writeFile(indexPath, await generateIndexHtml(docs), "utf8");
  return indexPath;
}

export async function renderAll(baseDir: string): Promise<number> {
  const docs = await scanDocuments(baseDir);
  let pages = 0;
  for (const doc of docs) {
    for (const kind of ["summary", "transcript"] as const) {
      const item = doc[kind];
      if (!item) continue;
      await writeDocumentHtml(doc, kind, item);
      item.htmlPath = join(doc.dir, `${kind}.html`);
      pages++;
    }
  }
  const indexPath = join(baseDir, "index.html");
  await writeFile(indexPath, await generateIndexHtml(docs), "utf8");
  return pages;
}

export function openInBrowser(htmlPath: string): Promise<void> {
  return new Promise((resolve, reject) => {
    let proc: ChildProcess;
    const { platform } = process;

    if (platform === "darwin") {
      proc = spawn("open", [htmlPath], { stdio: "ignore" });
    } else if (platform === "win32") {
      proc = spawn("cmd", ["/c", "start", "", htmlPath], {
        stdio: "ignore",
        shell: true,
      });
    } else {
      proc = spawn("xdg-open", [htmlPath], { stdio: "ignore" });
    }

    proc.on("error", () => {
      resolve();
    });

    proc.on("exit", () => {
      resolve();
    });

    setTimeout(() => resolve(), 5000);
  });
}
