import { fetchTranscript, listLanguages, toPlainText } from "youtube-transcript-plus";
import type { CaptionTrackInfo, TranscriptSegment } from "youtube-transcript-plus";

const NAME = "prosey";
const VERSION = "0.1.0";

function help(): string {
  return `${NAME} v${VERSION}

Usage: ${NAME} [options] <video-url-or-id>

Download a YouTube video transcript.

Arguments:
  video-url-or-id        YouTube URL (full or short) or bare video ID

Options:
  --lang <code>          Language code (e.g. en, fr). Auto-detect if omitted.
  -t, --timestamps       Include timestamps [MM:SS] in output.
  --list                 List available transcript languages and exit.
  -o, --output <path>    Write output to file instead of stdout.
  --json                 Output transcript as JSON array.
  --text                 Output as plain text (default).
  --no-decode-entities   Preserve HTML entities (decoded by default).
  --help                 Show this help message.
  --version              Show version.

Examples:
  ${NAME} dQw4w9WgXcQ
  ${NAME} https://www.youtube.com/watch?v=dQw4w9WgXcQ --lang es
  ${NAME} dQw4w9WgXcQ --timestamps -o transcript.txt
  ${NAME} dQw4w9WgXcQ --list
  ${NAME} dQw4w9WgXcQ --json`;
}

function formatTime(seconds: number): string {
  const m = Math.floor(seconds / 60);
  const s = Math.floor(seconds % 60);
  return `${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")}`;
}

function decodeEntities(text: string): string {
  return text.replace(/&#(\d+);/g, (_, code) => String.fromCharCode(Number(code)));
}

function formatWithTimestamps(segments: TranscriptSegment[], decode: boolean): string {
  return segments
    .map((s) => {
      const text = decode ? decodeEntities(s.text) : s.text;
      return `[${formatTime(s.offset)}] ${text}`;
    })
    .join("\n");
}

function toText(segments: TranscriptSegment[], decode: boolean): string {
  return segments
    .map((s) => (decode ? decodeEntities(s.text) : s.text))
    .join(" ")
    .replace(/ +/g, " ");
}

function toJSON(segments: TranscriptSegment[], decode: boolean): string {
  const data = segments.map((s) => ({
    text: decode ? decodeEntities(s.text) : s.text,
    offset: s.offset,
    duration: s.duration,
    timestamp: formatTime(s.offset),
  }));
  return JSON.stringify(data, null, 2);
}

function printLanguages(languages: CaptionTrackInfo[]): void {
  const rows = languages.map((l) => {
    const auto = l.isAutoGenerated ? " (auto-generated)" : "";
    return `  ${l.languageCode.padEnd(8)}${l.languageName}${auto}`;
  });
  console.log(`Available transcripts (${languages.length}):\n${rows.join("\n")}`);
}

const args = process.argv.slice(2);

if (args.length === 0 || args.includes("--help")) {
  console.log(help());
  process.exit(0);
}

if (args.includes("--version")) {
  console.log(VERSION);
  process.exit(0);
}

let videoId = "";
let lang: string | undefined;
let timestamps = false;
let listOnly = false;
let outputPath: string | undefined;
let outputJson = false;
let noDecode = false;

for (let i = 0; i < args.length; i++) {
  const arg = args[i];
  if (!arg) continue;
  if (arg === "--lang") {
    lang = args[++i] ?? undefined;
    if (!lang) {
      console.error("Error: --lang requires a language code");
      process.exit(1);
    }
  } else if (arg === "--timestamps" || arg === "-t") {
    timestamps = true;
  } else if (arg === "--list") {
    listOnly = true;
  } else if (arg === "-o" || arg === "--output") {
    outputPath = args[++i] ?? undefined;
    if (!outputPath) {
      console.error("Error: -o/--output requires a file path");
      process.exit(1);
    }
  } else if (arg === "--json") {
    outputJson = true;
  } else if (arg === "--text") {
    outputJson = false;
  } else if (arg === "--no-decode-entities") {
    noDecode = true;
  } else if (arg.startsWith("-")) {
    console.error(`Unknown option: ${arg}`);
    process.exit(1);
  } else {
    videoId = arg;
  }
}

if (!videoId) {
  console.error("Error: missing video URL or ID");
  console.log(help());
  process.exit(1);
}

try {
  if (listOnly) {
    const languages = await listLanguages(videoId);
    printLanguages(languages);
    process.exit(0);
  }

  const segments = lang ? await fetchTranscript(videoId, { lang }) : await fetchTranscript(videoId);

  const decode = !noDecode;

  const output = outputJson
    ? toJSON(segments, decode) + "\n"
    : timestamps
      ? formatWithTimestamps(segments, decode) + "\n"
      : toText(segments, decode) + "\n";

  if (outputPath) {
    await Bun.write(outputPath, output);
  } else {
    console.log(output);
  }
} catch (err: unknown) {
  const message = err instanceof Error ? err.message : String(err);
  console.error(`Error: ${message}`);
  process.exit(1);
}
