import { fetchTranscript, listLanguages } from "youtube-transcript-plus";
import type { CaptionTrackInfo, VideoDetails } from "youtube-transcript-plus";
import { formatWithTimestamps, toText, toJSON, formatDuration, decodeEntities } from "./format";

const NAME = "prosey";
const VERSION = "0.1.0";

function help(): string {
  return `${NAME} v${VERSION}

Usage: ${NAME} [options] <video-url-or-id>
       ${NAME} info [options] <video-url-or-id>

Download a YouTube video transcript or show video details.

Commands:
  info                  Show video metadata (title, channel, duration, etc.)

Arguments:
  video-url-or-id        YouTube URL (full or short) or bare video ID

Options:
  --lang <code>          Language code (e.g. en, fr). Auto-detect if omitted.
  -t, --timestamps       Include timestamps [MM:SS] in output.
  --list                 List available transcript languages and exit.
  -o, --output <path>    Write output to file instead of stdout.
  --json                 Output as JSON (incompatible with --details).
  --text                 Output as plain text (default).
  --details              Prepend video details to transcript (default).
  --no-details           Suppress video details, transcript only.
  --no-decode-entities   Preserve HTML entities (decoded by default).
  --help                 Show this help message.
  --version              Show version.

Examples:
  ${NAME} dQw4w9WgXcQ
  ${NAME} https://www.youtube.com/watch?v=dQw4w9WgXcQ --lang es
  ${NAME} dQw4w9WgXcQ -t -o transcript.txt
  ${NAME} dQw4w9WgXcQ --list
  ${NAME} dQw4w9WgXcQ --json --no-details
  ${NAME} dQw4w9WgXcQ --no-details
  ${NAME} info dQw4w9WgXcQ`;
}

function formatDetailsBlock(details: VideoDetails): string {
  const lines: string[] = [
    `Title:    ${decodeEntities(details.title)}`,
    `Channel:  ${details.author}`,
    `Duration: ${formatDuration(details.lengthSeconds)}`,
    `Views:    ${details.viewCount.toLocaleString()}`,
  ];

  if (details.description) {
    const desc = details.description.length > 500
      ? details.description.slice(0, 500) + "…"
      : details.description;
    lines.push(`Description:\n  ${desc.replace(/\n/g, "\n  ")}`);
  }

  return lines.join("\n");
}

function printVideoInfo(details: VideoDetails): void {
  const w = Math.max(
    "Title:".length,
    "Channel:".length,
    "Duration:".length,
    "Views:".length,
    "Video ID:".length,
    "Channel ID:".length,
    "Keywords:".length,
    "Description:".length,
  );
  const pad = (s: string) => s.padEnd(w);

  const lines: string[] = [
    `${pad("Title:")}      ${decodeEntities(details.title)}`,
    `${pad("Channel:")}    ${details.author}`,
    `${pad("Duration:")}   ${formatDuration(details.lengthSeconds)}`,
    `${pad("Views:")}      ${details.viewCount.toLocaleString()}`,
    `${pad("Video ID:")}   ${details.videoId}`,
    `${pad("Channel ID:")} ${details.channelId}`,
  ];

  if (details.keywords.length > 0) {
    lines.push(`${pad("Keywords:")}   ${details.keywords.join(", ")}`);
  }

  if (details.description) {
    lines.push(`${pad("Description:")}`);
    const descLines = details.description.split("\n").filter(Boolean);
    for (const line of descLines) {
      lines.push(`  ${line}`);
    }
  }

  console.log(lines.join("\n"));
}

function printLanguages(languages: CaptionTrackInfo[]): void {
  const rows = languages.map((l) => {
    const auto = l.isAutoGenerated ? " (auto-generated)" : "";
    return `  ${l.languageCode.padEnd(8)}${l.languageName}${auto}`;
  });
  console.log(`Available transcripts (${languages.length}):\n${rows.join("\n")}`);
}

const args = process.argv.slice(2);

if (args.length === 0 || args.includes("--help")) {
  console.log(help());
  process.exit(0);
}

if (args.includes("--version")) {
  console.log(VERSION);
  process.exit(0);
}

let mode = "transcript";
if (args[0] === "info") {
  mode = "info";
  args.splice(0, 1);
}

let videoId = "";
let lang: string | undefined;
let timestamps = false;
let listOnly = false;
let outputPath: string | undefined;
let outputJson = false;
let noDecode = false;
let showDetails = true;

for (let i = 0; i < args.length; i++) {
  const arg = args[i];
  if (!arg) continue;
  if (arg === "--lang") {
    lang = args[++i] ?? undefined;
    if (!lang) {
      console.error("Error: --lang requires a language code");
      process.exit(1);
    }
  } else if (arg === "--timestamps" || arg === "-t") {
    timestamps = true;
  } else if (arg === "--list") {
    listOnly = true;
  } else if (arg === "-o" || arg === "--output") {
    outputPath = args[++i] ?? undefined;
    if (!outputPath) {
      console.error("Error: -o/--output requires a file path");
      process.exit(1);
    }
  } else if (arg === "--json") {
    outputJson = true;
  } else if (arg === "--text") {
    outputJson = false;
  } else if (arg === "--details") {
    showDetails = true;
  } else if (arg === "--no-details") {
    showDetails = false;
  } else if (arg === "--no-decode-entities") {
    noDecode = true;
  } else if (arg.startsWith("-")) {
    console.error(`Unknown option: ${arg}`);
    process.exit(1);
  } else {
    videoId = arg;
  }
}

if (!videoId) {
  console.error("Error: missing video URL or ID");
  console.log(help());
  process.exit(1);
}

if (showDetails && outputJson) {
  console.error("Error: --details is incompatible with --json. Use --no-details to suppress video details.");
  process.exit(1);
}

try {
  if (mode === "info") {
    const result = await fetchTranscript(videoId, { videoDetails: true, lang } as any);
    if (outputJson) {
      console.log(JSON.stringify(result.videoDetails, null, 2));
    } else {
      printVideoInfo(result.videoDetails);
    }
    process.exit(0);
  }

  if (listOnly) {
    const languages = await listLanguages(videoId);
    printLanguages(languages);
    process.exit(0);
  }

  const decode = !noDecode;

  if (showDetails) {
    const config = lang ? { lang, videoDetails: true as const } : { videoDetails: true as const };
    const result = (await fetchTranscript(videoId, config)) as {
      videoDetails: VideoDetails;
      segments: { text: string; offset: number; duration: number; lang: string }[];
    };
    const detailsBlock = formatDetailsBlock(result.videoDetails);
    const transcript = timestamps
      ? formatWithTimestamps(result.segments, decode)
      : toText(result.segments, decode);
    const output = detailsBlock + "\n\n\n" + transcript + "\n";

    if (outputPath) {
      await Bun.write(outputPath, output);
    } else {
      console.log(output);
    }
  } else {
    const segments = lang ? await fetchTranscript(videoId, { lang }) : await fetchTranscript(videoId);

    const output = outputJson
      ? toJSON(segments, decode) + "\n"
      : timestamps
        ? formatWithTimestamps(segments, decode) + "\n"
        : toText(segments, decode) + "\n";

    if (outputPath) {
      await Bun.write(outputPath, output);
    } else {
      console.log(output);
    }
  }
} catch (err: unknown) {
  const message = err instanceof Error ? err.message : String(err);
  console.error(`Error: ${message}`);
  process.exit(1);
}
